# Generated by Django 2.1.7 on 2020-08-25 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200825_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlights',
            name='teamname',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.team'),
        ),
    ]
