# Generated by Django 2.1.7 on 2020-08-27 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200825_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='contestteam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamcontact', models.IntegerField(blank=True, null=True)),
                ('contactname', models.CharField(default=1, max_length=200)),
                ('teamown', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.team')),
            ],
        ),
        migrations.AlterField(
            model_name='highlights',
            name='teamname',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='app.team'),
        ),
    ]
