# Generated by Django 2.1.7 on 2020-08-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200827_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamname',
            field=models.CharField(blank=True, default='Team name', max_length=100, null=True),
        ),
    ]
